version: '3'
services:
  web:
    build: .
    ports:
      - "8009:80"
    volumes:
      - "./app:/var/www/html/app"
      - "./config:/var/www/html/config"
      - "./routes:/var/www/html/routes"
      - "./resources:/var/www/html/resources"
      - "./public:/var/www/html/public"
    tty: true
  db:
    image: mysql:5.7.9
    volumes:
      - ${HOME}/.dockerfs/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mydbpass
      MYSQL_DATABASE: mydatabase
    links:
      - web
